# publishes translation packages on nuget.org

name: Publish Stable Packages 

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build version number
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        VERSION="${VERSION//v}"
        echo "$VERSION"
        echo "nugetVersion=$VERSION" >> $GITHUB_ENV
        
    - name: Pack
      run: .\pack.ps1
      shell: pwsh

    - name: Push with dotnet
      run: dotnet nuget push **/*.nupkg -k ${{secrets.NUGET_API_KEY}} -n true -s https://api.nuget.org/v3/index.json --skip-duplicate
