# publishes translation packages on nuget.org

name: Publish Stable Packages 

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to publish (e.g. 3.0.0)'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build version number
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
        fi
        VERSION="${VERSION//v}"
        echo "$VERSION"
        echo "nugetVersion=$VERSION" >> $GITHUB_ENV
        
    - name: Pack
      run: .\pack.ps1
      shell: pwsh

    - name: NuGet login
      id: nuget-login
      uses: NuGet/login@v1
      with:
        user: Orchard

    - name: Push
      run: dotnet nuget push "**/*.nupkg" --api-key "${{ steps.nuget-login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
