# publishes translation packages on nuget.org

name: Publish Stable Packages 

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to publish (e.g. 3.0.0)'
        required: true
        type: string

jobs:
  publish:

    name: 📦 Publish to nuget
    permissions:
      id-token: write # Enables OIDC token generation

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v6

    - name: Build version number
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
        fi
        VERSION="${VERSION//v}"
        echo "$VERSION"
        echo "nugetVersion=$VERSION" >> $GITHUB_ENV
        
    - name: 🔑 Nuget trusted publishing
      uses: NuGet/login@v1
      id: login
      with:
        user: Orchard
        
    - name: Pack
      run: .\pack.ps1
      shell: pwsh

    - name: Push with dotnet
      run: dotnet nuget push **/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
